import { SectionTitle } from "@/components/section-title";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Download } from "lucide-react";
const skills = { "编程语言": ["TypeScript","JavaScript","Python","HTML/CSS"], "前端技术": ["React","Next.js","Vue","Tailwind CSS","shadcn/ui"], "后端技术": ["Node.js","Express","Prisma","PostgreSQL"], "工具平台": ["Git","Docker","Vercel","GitHub Actions"] };
export default function About() {
  return (<div className="px-6 pt-28"><div className="grid gap-16 lg:grid-cols-5"><div className="lg:col-span-2"><div className="sticky top-24"><div className="aspect-square w-full max-w-xs rounded-2xl bg-gradient-to-br from-primary/20 to-accent" /><div className="mt-6"><h1 className="text-2xl font-bold">王梓杰</h1><p className="mt-1 text-muted-foreground">前端开发工程师</p><div className="mt-6 flex gap-3"><Button asChild><Link href="mailto:wzj@example.com">联系我</Link></Button><Button variant="outline" asChild><Link href="#"><Download className="mr-1 h-4 w-4" />下载简历</Link></Button></div></div></div></div><div className="lg:col-span-3"><SectionTitle title="关于我" subtitle="热衷于创造优秀的 Web 体验" /><div className="text-lg leading-relaxed text-muted-foreground space-y-4"><p>你好！我是王梓杰，一名专注于前端开发的工程师。</p><p>我擅长使用 React 和 Next.js 构建现代化 Web 应用。</p><p>工作之余我喜欢写技术博客分享学习心得。</p></div><div className="mt-12">{Object.entries(skills).map(([cat, items]) => <div key={cat} className="mb-6"><h4 className="mb-3 text-sm font-medium text-muted-foreground uppercase tracking-wider">{cat}</h4><div className="flex flex-wrap gap-2">{items.map(s => <Badge key={s} variant="secondary" className="text-sm py-1 px-3">{s}</Badge>)}</div></div>)}</div><div className="mt-16 border-t border-border pt-8"><h3 className="text-xl font-semibold">联系方式</h3><p className="mt-2 text-muted-foreground">欢迎随时联系我！</p><Link href="mailto:wzj@example.com" className="mt-2 inline-block text-primary underline-offset-4 hover:underline">wzj@example.com</Link></div></div></div></div>);
}
